import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";
import { ProviderRedux } from "@/store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ProviderRedux>
      <html lang="en">
        <body className={inter.className}>
          <div className="wrapper-layout">
            <header className="header-layout">
              <Header />
            </header>
            <main className="main-layout">{children}</main>
          </div>
        </body>
      </html>
    </ProviderRedux>
  );
}
